### ISSUE TITLE
Typo in chapter 3 - preface

### ISSUE THREAD

**Issue by balroggg** [skerkour/black-hat-rust#11]
> I quickly realized that studying law was not for me: reality was travested

`travested` -> `travestied`

> The goal of this book this is to save

maybe double `this`

> It’s important to understand that Black Hat Rust is not meant to be an
big encyclopaedia

`encyclopaedia` -> `encyclopedia`

> Tt took me

maybe `Tt` -> `That`

> but It’s only when

`It's` -> `it's`

**Comment by pmurzin** [comment]
> we are frantically typing on all days long work hunder the hood

`hunder` -> `under`

> because Windows was to slow

`to `-> `too`

> sand started to learn to develop C++ programs with Qt

`sand `-> `and`

> to learn low-level progrmaming

`progrmaming `-> `programming`

> but I have do my best to list the best resources to further your learning journey.

Maybe  `I have do` -> `I will do `

>Knowledge don’t move mountains. . Action do

`don't `-> `doesn't`, `Action `-> `Actions`

**Comment by RedPenguin101** [comment]
> It was deeply frustarting for the young man I was,

`frustrating` -> `frustrating`

**Comment by skerkour** [comment]
Thank you very much 🙏

I've fixed the typos. The edited version will be released, I hope, by the end of next week.


Kind regards
