### ISSUE TITLE
Sha1 Cracker requires `use hex;`

### ISSUE THREAD

**Issue by nwisemanII** [skerkour/black-hat-rust#129]
I am currently using 
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
```
I noticed that the code for the sha1 cracker requires the use of
```
use hex;
```
in the import(?)/use section of the code in order for the compiler to recognize `&hex...` in this line https://github.com/skerkour/black-hat-rust/blob/92d3b265fc4b45e07d1940007d1139347fcd77c1/ch_01/sha1_cracker/src/main.rs#L31

**Comment by skerkour-dev** [comment]
Hi @nwisemanII 

You don't need to use `use` here because `hex` is the name of the crate. 

We could have used:
```rust
use hex::encode;

// ...


if hash_to_crack == &encode(...);
```

But it makes the code less readable in my opinion.

You can learn more about the `use` keyword here: https://doc.rust-lang.org/std/keyword.use.html
