### ISSUE TITLE
Code block font size too large

### ISSUE THREAD

**Issue by pkazmier** [skerkour/black-hat-rust#13]
I think the book would benefit from a smaller font size for code blocks. In both the PDF and epub versions (didn’t look at mobi), the code block font looks larger than the body text font. To minimize wrapping of code blocks, I think a smaller monospace font size would look better. It would also look more harmonious with the body font size. 

(Same comment applies to your blog posts IMO). 

For example, here is a screenshot from the Rust Book, which I think has the right proportion of body font size to code block size:

![IMG_0391](https://user-images.githubusercontent.com/747855/132785331-5f97b2ef-c5f4-49ca-beae-1d315883a306.png)

**Comment by skerkour** [comment]
Thank you very much for the feedback!

I agree with you, and will try to fix it for the next version (v2021.18), it should be a simple matter of tweaking some [pandoc](https://pandoc.org/) flag / adjusting some CSS.

Regarding the blog, it's now fixed :)

**Comment by skerkour** [comment]
* [x] epub
* [x] mobi
* [ ] pdf

**Comment by skerkour** [comment]
Fixed in v2021.40 :)
