### ISSUE TITLE
sha1_cracker: unnecessary allocation in loop?

### ISSUE THREAD

**Issue by pkazmier** [skerkour/black-hat-rust#14]
_Disclaimer: I'm new to Rust, but making my way through both your book and Rust Programming 2nd edition._

While looking at this line in SHA1 cracker, I was curious why `to_string` was required. Specifically, I wanted to know if the rest of the code could use a `&str` instead, so a heap allocation could be avoided. 

https://github.com/skerkour/black-hat-rust/blob/9da1dd3c992e436887612bf8e21f4bd220cc0a70/ch_01/sha1_cracker/src/main.rs#L29

After removing the `to_string`, I discovered that the code would not compile due to the error "temporary value dropped while borrowed". After reasoning about this error, it made sense. Although `Result` contains the owned string, when it is extracted with `?`, the value is not assigned anywhere, so the `&str` reference returned from `trim` points to a value that is dropped.

So, I changed the line above to the following two lines, where I save the `String` value to a variable, so the `&str` returned from `trim` had a valid place to point:

```rust 
        let line = line?;
        let common_password = line.trim();
```

Although this compiled, I was still unsure if this would make a difference as I have no experience with Rust or how smart the compiler is or isn't, so I ran some tests, which showed the version without the `to_string` is faster and avoids extra heap allocations. Perhaps the code in the book could be tweaked to eliminate this, seemingly, unnecessary call?

**Comment by skerkour** [comment]
Hello @pkazmier, nice catch! You are totally right, allocating a variable on the stack is way, way cheaper than a Heap allocation.

I've updated the code and it will appear in version of the book :)


But just to be clear, this program is a toy example, using a GPU cracker such as Hashcat will yield far, far better results (https://gist.github.com/epixoip/a83d38f412b4737e99bbef804a270c40).

Best regards
