### ISSUE TITLE
Letter 'e' is disturbing to read in .pdf format

### ISSUE THREAD

**Issue by legezam** [skerkour/black-hat-rust#16]
Hi!

Thanks for creating this book. I have just started reading the pdf version and i noticed the letter 'e' is undistinguishable from 'c' letter which makes it a bit hard to read. Would it be possible to change that?

![Screenshot from 2021-09-27 11-35-52](https://user-images.githubusercontent.com/3974359/134884125-b7d57d5e-f5ee-4c65-97f3-74cc15e83211.png)

I am facing no difficulties with reading any other text on internet so this must be something with the formatting of this book.

Thanks!

**Comment by legezam** [comment]
Sorry, it was me being stupid. closing :)

**Comment by skerkour** [comment]
Dear @legezam

I'm glad that this is finally not an issue. Out of curiosity, because your screenshot is really disturbing to me, what was causing this issue?

**Comment by legezam** [comment]
I was reading it from some sort of preview application that i can't remember correctly. Downloading and opening in firefox gave a very good experience on the same machine.
