### ISSUE TITLE
False Friend (Typo) in Chapter 6 (6.10.1)

### ISSUE THREAD

**Issue by DATADEER** [skerkour/black-hat-rust#163]
Hey Sylvain,
thanks for putting all the time and effort into writing this great book. 🙌 It‘s a truly exciting way to learn Rust.

I‘ve spotted a tiny mistake in “_I think that I don’t need to write a **roman** for you to understand how harmful it can be._” (6.10.1)
I believe the word „roman“ is not used to describe a „novel“ in english. I guess this word has sneaked into the text as a „false friend“ from french? 🙂

Keep on writing that good stuff 🤩

**Comment by zesty** [comment]
perhaps "roman à clef" was intended? definitely in English usage, and good because of the cryptography angle

https://en.wikipedia.org/wiki/Roman_%C3%A0_clef
