### ISSUE TITLE
Would you be interested in some kind of community?

### ISSUE THREAD

**Issue by skerkour** [skerkour/black-hat-rust#18]
I've received many request to create some kind of community about Rust x Hacking.

To be clear I don't have the bandwidth today to do that.

But as this is a really interesting thing that I could set up in the future, I want to gather some feedback before.

The biggest advantage of a community is peer-to-peer learning, where everyone can share their discoveries.

The biggest disadvantages of a community around security are identities and potential scams.

To be honest, I'm not a fan of chat communities (Discord, Matrix...): The knowledge is quickly lost, and it's very easy to mix a lot of conversations.

I would prefer a forum, which provide a searchable archive.

What do you think about it? What would you prefer, and why?

**Comment by chalmagean** [comment]
Would be great to have a [Discourse](https://www.discourse.org/)

**Comment by netzeroo** [comment]
I have experience with moderating subreddits so I created https://www.reddit.com/r/rust_security, would love more moderators and people willing to contribute there.
