### ISSUE TITLE
Page 7 word choice conflate -> inflate

### ISSUE THREAD

**Issue by aeonik** [skerkour/black-hat-rust#2]
Hello,
On page 7 under the subheading "Attacks without a clear goal" 

The phrase "conflate their ego" should be reworded to "inflate their ego".

Regards,
Aeonik

**Comment by skerkour** [comment]
Fixed, Thank you very much!
As the first chapter is being rewritten (improved), the "fix" will published at the same time than chapter 2, in ~2.5 week I expect.
