### ISSUE TITLE
comment error

### ISSUE THREAD

**Issue by rvolz** [skerkour/black-hat-rust#20]
FWIW, an unclosed comment in chapter 3 produces this message

<img width="488" alt="CleanShot 2021-10-10 at 08 18 38@2x" src="https://user-images.githubusercontent.com/1092531/136684988-478e9341-8c28-4156-94b6-9b7048c9a19f.png">
s

**Comment by skerkour** [comment]
Fixed, Thank you very much 🙏

**Comment by skerkour** [comment]
Added, Thank you!

Now everything seems to be fine (other than a not passing a regexp, but it seems to be an error on epubcheck's side).
