### ISSUE TITLE
Question: Do you have a preview? How about a student discount?

### ISSUE THREAD

**Issue by rpruizc** [skerkour/black-hat-rust#22]
Basically that. I'm looking into maybe suggest this book for a few students. Before doing so, I'd like to read a little of it if possible.
Unfortunately, our budget is very limited right now, but I believe this could be a great asset for my class.

Thanks!

**Comment by skerkour** [comment]
Dear @rpruizc,

Thank you for reaching out!

At the moment there is no PDF preview available as the book is still work in progress and things are moving fast!

That being said, I regularly share some excerpts on my blog: https://kerkour.com/tags/hacking/

You can subscribe to the blog here to be alerted once the book is complete and a preview is available: https://kerkour.com/subscribe/

Regarding the student discount it will be a pleasure. Could you send me an email: https://kerkour.com/about/#contact--social-

Kind regards

**Comment by rpruizc** [comment]
Thank you. I just sent you an email.
