### ISSUE TITLE
question: what I need to know before I read the book?

### ISSUE THREAD

**Issue by falcongx** [skerkour/black-hat-rust#23]
rust is my first programming language I am still trying to figure out my way in programing I did read few books and each one tackled subject I had no prior experience in and I did not get the most of the books but I tried to get as much as I can from them I was wandering if the "rust black hat" is required to have prior knowledge in some topics and if there are some what are thy  

PS: forgive me for my bad English its not my first language

**Comment by skerkour** [comment]
Thank you 🙏
You can follow the progress by subscribing to my blog (https://kerkour.com/subscribe/) or subscribing to the issue tracking the roadmap: https://github.com/skerkour/black-hat-rust/issues/25

Best
