### ISSUE TITLE
Typo in chapter 14

### ISSUE THREAD

**Issue by kmdivi** [skerkour/black-hat-rust#27]
> But waht is the format of a phone number?

`waht` -> `what`

> What are the verifications to preceed to when creating a job for an agent? This is the role of the service layer.

`preceed` -> `proceed`

> The service layer is wher ethe business logic lives. All our application’s rules and invariants lives in the service layer.

`wher ethe` -> `where the`

> In our case, the entities will Agent , Job (a job is a command created by the client, stored and dispatched by the server, and exectued by the agent),

`exectued` -> `executed`

> The repository layer is a thin abtraction over the database. It encapsulates all the database calls.

`abtraction` -> `abstraction`

**Comment by skerkour** [comment]
Fixed, Thank you very much 🙏
