### ISSUE TITLE
Book Typos?

### ISSUE THREAD

**Issue by moomoolive** [skerkour/black-hat-rust#34]
Hey Sylvain,

I've just started the book and the introduction has been really excited! Looking forward to an awesome read.

I found a typo in the black hat book (section 5.3.2), where do I file the edit?

**Comment by skerkour** [comment]
Hey @moomoolive ,

Thank you very much for the kind words!

Feel free to post here or by email any typos you find and I will correct them with pleasure :)

**Comment by skerkour** [comment]
Ideally with the PDF page number, or the section.

**Comment by moomoolive** [comment]
sounds good, I'll send you an email
