### ISSUE TITLE
Table of Contents alignment issues

### ISSUE THREAD

**Issue by rjray** [skerkour/black-hat-rust#35]
In the version v2021.41, the alignment of ToC headings with their section numbers is missing spaces in the chapters from 10 onward.

**Comment by skerkour** [comment]
Hi @rjray Thank you for the report!

After some investigations, I've been unable to fix this problem. [pandoc](https://pandoc.org) seems to offer no option to configure the Table of Content's layout.

I'll keep this issue open in case I (or someone else) find a solution :)

Best

**Comment by skerkour** [comment]
After more time than reasonable spent on this issue, I can't find a solution, so I will close this issue.

Thus I will close it, but if by chance a pandoc wizard pass by, any help is appreciated :)
