### ISSUE TITLE
Some artifacts in the 2021.41 version

### ISSUE THREAD

**Issue by NightlySide** [skerkour/black-hat-rust#38]
It seems that some mistakes were made during the md -> pdf conversion : 

* listings are overflowing on the right side for every console command
* chapter referencing is off by several chapters, e.g. talking about chapter 5 is actually talking about chapter 7 and so on

I'll update the list while I'm going through the book

**Comment by skerkour** [comment]
Hey @NightlySide thank you very much for the report!

I'll try to fix these issues before the end of the weekend.

Best regards

**Comment by NightlySide** [comment]
Page 72 of the PDF version you have to listings called `fn fold()` instead of the first being `fn reduce()`

**Comment by NightlySide** [comment]
Page 76 of the PDF, the listings says Otpion<...> instead of Option<...>

**Comment by skerkour** [comment]
I've fixed the typos (+ many more) in `v2021.43` that is now online.

I'll need more time for the layout issues :)

**Comment by NightlySide** [comment]
No problem :) glab i'll be of some help

**Comment by skerkour** [comment]
I just uploaded `v2021.45` with all these issues (+many more) fixed 🎉
