### ISSUE TITLE
Chapter 3: Typos

### ISSUE THREAD

**Issue by pejato** [skerkour/black-hat-rust#41]
Hi @skerkour , enjoying the book!

Ran across some minor typos in ch3 and thought I'd list them here.

* 3.7.1, "Instead, by calling `spaw_blocking`" -> "Instead, by calling `spawn_blocking`"
* 3.9.1.2, "Cosuming iterators" -> "Consuming iterators"
* 3.9.1.2, "for_each is the functionnal" -> "for_each is the functional"
* 3.9.5.1 "when an initial Future finisehd:" -> "when an initial Future finished:"
  * This might actually be better as "when an initial Future finishes:"

**Comment by skerkour** [comment]
Dear @pejato Thank you very much for reporting these issues!

I've now uploaded a new version with the typos corrected.

If you find other issues, please don't hesitate to report them here.
