### ISSUE TITLE
Chapter 2 feedback

### ISSUE THREAD

**Issue by tylerhjones** [skerkour/black-hat-rust#50]
Chapter 2 skips over the models file, and several external libraries. It might be important to 

- explain adding these external libraries and include the import lines demonstrating how to import / add external libraries.
- local crate references in imports, how to import files in a project.
- project hierarchy and structures. (at this point ch2. i wouldnt expect a real tree structure, but maybe address the models file and its common practices)
- adding deps with cargo
- explain the rayon crate
- explain the serde crate
- explain the reqwest crate

 Very beginner things, but it is chapter 2. I would expect these things to be explained in a book which advertises learning rust along the way.

**Comment by tylerhjones** [comment]
either this, or mention in the chapter that you expect the reader to supplement the examples by reading the repo source and that the book does not include all information; ellipsis things like imports, crates, etc.

**Comment by skerkour** [comment]
Hey @tylerhjones Thank you very much for this feedback!

I've created an internal ticket and will act on it during my next Black Hat Rust's edition round :)

Best regards ✌️
