### ISSUE TITLE
Ch2. serde Deserialize feature not explicit

### ISSUE THREAD

**Issue by tylerhjones** [skerkour/black-hat-rust#51]
```
info: The currently active `rustc` version is `rustc 1.63.0-nightly (cd282d7f7 2022-05-18)`
```
```toml
[dependencies]
anyhow = "1.0.57"
rayon = "1.5.3"
serde = "1.0.137"
thiserror = "1.0.31"
```
My model.rs file is the same as https://github.com/skerkour/black-hat-rust/blob/main/ch_02/tricoder/src/model.rs
yet the compiler complains
```
error: cannot find derive macro `Deserialize` in this scope
  --> src/model.rs:15:17
   |
15 | #[derive(Debug, Deserialize, Clone)]
   |                 ^^^^^^^^^^^
   |
note: `Deserialize` is imported here, but it is only a trait, without a derive macro
  --> src/model.rs:1:5
   |
1  | use serde::Deserialize;
   |     ^^^^^^^^^^^^^^^^^^
```

Your repo shows this import as a feature inclusion;
```toml
serde = { version = "1", features = ["derive"] }
```
but this is never mentioned in the book afaict.

**Comment by tylerhjones** [comment]
I knew this error from prior experience, but it may not be know to other readers.

**Comment by skerkour** [comment]
Thank you for the feedback!

At the moment I have no plan to change this, as I consider the GitHub repository as the source of truth for the code, while the book explains the code concepts.

The `features` feature was ruled out of scope of the book, but if more people report being confused, I may revisit this decision :)

**Comment by tylerhjones** [comment]
👍🏻
