### ISSUE TITLE
Chapter 2 typos

### ISSUE THREAD

**Issue by nicholastmosher** [skerkour/black-hat-rust#54]
Hi there, I'm reading through the book and loving it so far! In chapter 2 right now and noticed a typo and another potential typo:

In `2.14`:

> Also, the parallel iterator has the same method available as traditional iterators

I believe "method" should be "methods"

And in `2.15`:

> Indeed, by using `threadpool` of `std::thread::spawm`

- `spawm` should be `spawn`,
- and also, should it say "by using `threadpool` _instead of_ `std::thread::spawn`?

Apologies if this is not the best place to send suggestions, let me know if you'd prefer them another way!

**Comment by skerkour** [comment]
Thank you very much @nicholastmosher , this is the perfect place to report typos :)

It's now fixed.

> Indeed, by using `threadpool` of `std::thread::spawn`

Should actually day: Indeed, by using `threadpool` instead of `rayon` :)
