### ISSUE TITLE
Usage help text should be written in bnf

### ISSUE THREAD

**Issue by zeddee** [skerkour/black-hat-rust#7]
We should be writing help text using [BNF](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form),

- where square brackets `[]` are used to denote optional args, and
- angled brackets `<>` are used to denote required args.

So instead of:

```
sha1_cracker: [wordlist.txt] [sha1_hash]
```

we should write:

```
sha1_cracker: <wordlist.txt> <sha1_hash>
```

**Comment by skerkour** [comment]
Fixed in 7e09754dafbb424039e24b7171befbcb726764a5

Thank you @zeddee!
