### ISSUE TITLE
About the latest post of build a web-app with rust & wasm

### ISSUE THREAD

**Issue by azusachino** [skerkour/black-hat-rust#78]
I was not familiar with yew and wasm, so I'm learning from your post, thank you for your great post.
But, the problem is, it seems like there are **huge** changes between yew-0.18 and yew-0.19, it's almost impossible to follow your instructions. So, I don't know if you have to plan to use the `new yew` and update the post or something like that... 
Or maybe, I will follow the docs to get familiar with yew (the slow way). 
Anyway, a big thanks.

**Comment by skerkour** [comment]
Hello @azusachino ,

I actually updated all the dependencies of the projects of this repository last week, but it seems that I inadvertently missed the ones in the `phishing` folder.

I'll do it as soon as possible :)

**Comment by azusachino** [comment]
That's very nice of you. 
I will close this issue now.
