### ISSUE TITLE
Request: Add an open-source license

### ISSUE THREAD

**Issue by sudo6756** [skerkour/black-hat-rust#85]
Hello, please consider adding an open-source license to this repository.  A comparison of common licenses can be found at [https://choosealicense.com/](https://choosealicense.com/).  A potential candidate might be the MIT license, or if you want pretty much no restrictions on it, the Unlicense would work well.  If you would prefer something with a few more rules, the GNU GPLv3 could be good too.

**Comment by skerkour** [comment]
Hi @sudo6756 Thank you for the heads up!

I was sure that a LICENSE file was present. It's now fixed :)

✌️
