### ISSUE TITLE
Citation File

### ISSUE THREAD

**Issue by sudo6756** [skerkour/black-hat-rust#86]
Hello, I am citing this repository in a project that I have done, but there is not CITATION.cff file to show the correct citation for this repository. Please consider adding such a file in order to enable others in the future to have what they need to properly cite your work.

For more information on this, here are a couple of GitHub links on how to make such a file:
https://citation-file-format.github.io/
https://github.com/citation-file-format/citation-file-format

**Comment by skerkour** [comment]
Done! Thank you for the recommendation!
